### PR TITLE
[T-6565][16.0][MIG] mail_show_follower

### PR DESCRIPTION
**Pull request by manuelregidor**
@ValentinVinagre @HaraldPanten The module has been refactored and tests have been added.

@Jaimermaccione could you review, please?

T-6565

### CODE REVIEW

**Review by ValentinVinagre — CHANGES_REQUESTED** [review]
More "simple" than before, I like the change :). 
Check out the contributors please, only sygel participated in this module.

**Review by Jaimermaccione — APPROVED** [review]
@manuelregidor LGTM! Functional review on local enviroment.

**Comment by manuelregidor** [comment]
@ValentinVinagre Changes made. Could you review, please?

**Review by ValentinVinagre — APPROVED** [review]
👍🏻 LGTM

**Pull request merged**
